name: Run Polkadot action
description: Reusable action to build and run a modified version of Polkadot
inputs:
  polkadot-version:
    description: 'Version tag, e.g. polkadot-v1.7.1'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.3.0
      with:
        path: substrate-tip-bot
    - uses: actions/checkout@v3.3.0
      with:
        repository: paritytech/polkadot-sdk
        ref: ${{ inputs.polkadot-version }}
        path: polkadot-sdk
    - name: Apply Polkadot patches
      run: git apply ../substrate-tip-bot/polkadot.e2e.patch
      shell: bash
      working-directory: polkadot-sdk
    - name: Restore cached Polkadot build
      id: polkadot-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          polkadot-sdk/target/release
        key: ${{ runner.os }}-${{ inputs.polkadot-version }}-${{ hashFiles('substrate-tip-bot/polkadot.e2e.patch') }}
    - name: Build Polkadot
      if: steps.polkadot-cache-restore.outputs.cache-hit != 'true'
      run: |
        cargo build --release --locked --features=fast-runtime -p polkadot
      shell: bash
      working-directory: polkadot-sdk
    - name: Save Polkadot build cache
      uses: actions/cache/save@v3
      with:
        path: |
          polkadot-sdk/target/release
        key: ${{ runner.os }}-${{ inputs.polkadot-version }}-${{ hashFiles('substrate-tip-bot/polkadot.e2e.patch') }}
    - name: Run a local Rococo node
      run: |
        polkadot-sdk/target/release/polkadot --rpc-external --no-prometheus --no-telemetry --chain=rococo-dev --tmp --alice --execution Native --rpc-port 9902 &
        until curl -s '127.0.0.1:9902'; do sleep 3; done
      shell: bash
