name: Publish and deploy

on:
  push:
    branches:
      - master
    tags:
      - v*
      - stg-v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

#to use reusable workflow
permissions:
  id-token: write
  contents: read

env:
  APP: "substrate-tip-bot"

jobs:
  set-variables:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      DATE_TAG: ${{ steps.version.outputs.DATE_TAG }}
    steps:
      - name: Define version
        id: version
        run: |
          export COMMIT_SHA=${{ github.sha }}
          export COMMIT_SHA_SHORT=${COMMIT_SHA:0:8}
          export REF_NAME=${{ github.ref_name }}
          echo "DATE_TAG=$(date -u +'%Y%m%d-%H%M%S')-${COMMIT_SHA_SHORT}" >> ${GITHUB_OUTPUT}
          export REF_SLUG=${REF_NAME//\//_}
          echo "short sha: ${COMMIT_SHA_SHORT}  slug: ${REF_SLUG}"
          if [[ ${REF_SLUG} == "master" ]]
          then
            export VERSION=${REF_SLUG}-${COMMIT_SHA_SHORT}
            echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          else
            export VERSION=${REF_SLUG}
            echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          fi
          echo "set VERSION=${VERSION}"
  build_push_docker:
    name: Build docker image
    runs-on: ubuntu-latest
    environment: master_n_tags
    needs: [set-variables]
    env:
      VERSION: ${{ needs.set-variables.outputs.VERSION }}
      DATE_TAG: ${{ needs.set-variables.outputs.DATE_TAG }}
      IMAGE_NAME: "docker.io/paritytech/substrate-tip-bot"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.DATE_TAG }}
